import { FormEvent, useEffect, useMemo, useState } from 'react';
import { ApiError, api } from './api';
import { clearSession, loadSession, saveSession, type Session } from './auth';
import { privacyNotice, PRIVACY_NOTICE_VERSION, terms } from './legal';
import { passwordStrength, type FieldErrors, type SignupValues, validateLogin, validateSignup } from './validation';
import type { Dashboard, Frequency, Habit, HabitPayload, HabitWithStreak, RegistrationPayload, Streak } from './types';

type View = 'dashboard' | 'habits' | 'profile';
const todayKey = () => new Date().toISOString().slice(0, 10);

function errorMessage(error: unknown) { return error instanceof Error ? error.message : 'Something went wrong. Please try again.'; }
function initials(email: string) { return email.slice(0, 2).toUpperCase(); }

const emptySignup: SignupValues = { username: '', firstName: '', middleName: '', lastName: '', age: '', email: '', phone: '', password: '', confirmPassword: '', termsAccepted: false };
function FieldError({ message }: { message?: string }) { return message ? <small className="field-error" role="alert">{message}</small> : null; }
function PasswordMeter({ password }: { password: string }) { const strength = passwordStrength(password); return <div className="password-meter" aria-live="polite"><div className="meter-bars">{[1, 2, 3, 4, 5].map(level => <i key={level} className={level <= strength.score ? `meter-${strength.score}` : ''} />)}</div><span>{password ? `${strength.label}${strength.checks.length ? ` · needs ${strength.checks.join(', ')}` : ''}` : 'Use 8+ characters, uppercase, lowercase, number, and symbol.'}</span></div>; }

function AuthScreen({ onAuthenticated }: { onAuthenticated: (session: Session) => void }) {
  const [mode, setMode] = useState<'login' | 'register'>('login');
  const [email, setEmail] = useState(''); const [password, setPassword] = useState(''); const [signup, setSignup] = useState<SignupValues>(emptySignup); const [touched, setTouched] = useState<Set<string>>(new Set()); const [legal, setLegal] = useState<'terms' | 'privacy' | null>(null);
  const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const errors: FieldErrors = mode === 'register' ? validateSignup(signup) : validateLogin(email, password);
  const fieldError = (field: keyof FieldErrors) => touched.has(field) ? errors[field] : undefined;
  const touch = (field: keyof FieldErrors) => setTouched(previous => new Set(previous).add(field));
  const updateSignup = <K extends keyof SignupValues>(field: K, value: SignupValues[K]) => setSignup(previous => ({ ...previous, [field]: value }));
  const switchMode = () => { setMode(current => current === 'login' ? 'register' : 'login'); setError(''); setTouched(new Set()); };
  const submit = async (event: FormEvent) => {
    event.preventDefault(); setError('');
    if (Object.keys(errors).length) { setTouched(new Set(mode === 'register' ? Object.keys(emptySignup) : ['loginEmail', 'loginPassword'])); setError('Please correct the highlighted fields.'); return; }
    setLoading(true);
    try {
      const result = mode === 'login' ? await api.login(email, password) : await api.register({ username: signup.username, firstName: signup.firstName, middleName: signup.middleName || undefined, lastName: signup.lastName, age: Number(signup.age), email: signup.email, password: signup.password, phone: signup.phone, termsAccepted: true, privacyVersion: PRIVACY_NOTICE_VERSION } satisfies RegistrationPayload);
      if (!result.accessToken) { setError('Check your inbox to confirm your account, then sign in.'); return; }
      onAuthenticated({ token: result.accessToken, user: result.user });
    } catch (caught) { setError(errorMessage(caught)); } finally { setLoading(false); }
  };
  const legalContent = legal === 'terms' ? terms : privacyNotice;
  const legalTitle = legal === 'terms' ? 'Terms of Service' : 'Privacy Notice';
  return <main className="auth-layout"><section className="auth-intro"><p className="eyebrow">A quieter way to keep promises</p><h1>Make room<br />for progress.</h1><p>Tempo keeps your habits clear, close, and easy to return to.</p><div className="intro-note"><span>✦</span><span>Small actions, considered daily.</span></div></section><section className="auth-panel"><div className="brand">tempo<span>•</span></div><div className="auth-card"><p className="eyebrow">{mode === 'login' ? 'Welcome back' : 'Begin gently'}</p><h2>{mode === 'login' ? 'Sign in to your rhythm.' : 'Create your space.'}</h2><p className="muted">{mode === 'login' ? 'Your habits are waiting for you.' : 'A little structure can go a long way.'}</p><form noValidate onSubmit={submit} aria-describedby={error ? 'auth-error' : undefined}>
    {mode === 'register' && <><label htmlFor="username">Username<input id="username" required autoComplete="username" value={signup.username} onChange={e => updateSignup('username', e.target.value)} onBlur={() => touch('username')} placeholder="alex_h" aria-invalid={!!fieldError('username')} /><FieldError message={fieldError('username')} /></label><div className="name-grid"><label htmlFor="first-name">First name<input id="first-name" required autoComplete="given-name" value={signup.firstName} onChange={e => updateSignup('firstName', e.target.value)} onBlur={() => touch('firstName')} placeholder="Alex" aria-invalid={!!fieldError('firstName')} /><FieldError message={fieldError('firstName')} /></label><label htmlFor="middle-name">Middle name <span className="optional">(optional)</span><input id="middle-name" autoComplete="additional-name" value={signup.middleName} onChange={e => updateSignup('middleName', e.target.value)} onBlur={() => touch('middleName')} placeholder="Morgan" aria-invalid={!!fieldError('middleName')} /><FieldError message={fieldError('middleName')} /></label></div><label htmlFor="last-name">Last name<input id="last-name" required autoComplete="family-name" value={signup.lastName} onChange={e => updateSignup('lastName', e.target.value)} onBlur={() => touch('lastName')} placeholder="Hill" aria-invalid={!!fieldError('lastName')} /><FieldError message={fieldError('lastName')} /></label><label htmlFor="age">Age<input id="age" required type="number" min="13" max="120" inputMode="numeric" value={signup.age} onChange={e => updateSignup('age', e.target.value)} onBlur={() => touch('age')} placeholder="25" aria-invalid={!!fieldError('age')} /><FieldError message={fieldError('age')} /></label></>}
    <label htmlFor={mode === 'login' ? 'login-email' : 'signup-email'}>Email<input id={mode === 'login' ? 'login-email' : 'signup-email'} required type="email" autoComplete="email" value={mode === 'login' ? email : signup.email} onChange={e => mode === 'login' ? setEmail(e.target.value) : updateSignup('email', e.target.value)} onBlur={() => touch(mode === 'login' ? 'loginEmail' : 'email')} placeholder="you@example.com" aria-invalid={!!fieldError(mode === 'login' ? 'loginEmail' : 'email')} /><FieldError message={fieldError(mode === 'login' ? 'loginEmail' : 'email')} /></label>
    {mode === 'register' && <label htmlFor="phone">Philippine mobile number<input id="phone" required type="tel" inputMode="tel" autoComplete="tel-national" value={signup.phone} onChange={e => updateSignup('phone', e.target.value)} onBlur={() => touch('phone')} placeholder="0917 123 4567" aria-label="Philippine mobile number" aria-describedby="phone-help" aria-invalid={!!fieldError('phone')} /><small id="phone-help">Philippine mobile numbers only. We use it for your account record, not marketing.</small><FieldError message={fieldError('phone')} /></label>}
    <label htmlFor={mode === 'login' ? 'login-password' : 'signup-password'}>Password<input id={mode === 'login' ? 'login-password' : 'signup-password'} required type="password" autoComplete={mode === 'login' ? 'current-password' : 'new-password'} value={mode === 'login' ? password : signup.password} onChange={e => mode === 'login' ? setPassword(e.target.value) : updateSignup('password', e.target.value)} onBlur={() => touch(mode === 'login' ? 'loginPassword' : 'password')} placeholder="••••••••" aria-invalid={!!fieldError(mode === 'login' ? 'loginPassword' : 'password')} /><FieldError message={fieldError(mode === 'login' ? 'loginPassword' : 'password')} /></label>
    {mode === 'register' && <><PasswordMeter password={signup.password} /><label htmlFor="confirm-password">Confirm password<input id="confirm-password" required type="password" autoComplete="new-password" value={signup.confirmPassword} onChange={e => updateSignup('confirmPassword', e.target.value)} onBlur={() => touch('confirmPassword')} placeholder="••••••••" aria-invalid={!!fieldError('confirmPassword')} /><FieldError message={fieldError('confirmPassword')} /></label><label className="consent-control"><input required type="checkbox" checked={signup.termsAccepted} onChange={e => { updateSignup('termsAccepted', e.target.checked); touch('termsAccepted'); }} /><span>I agree to the <button type="button" className="text-button" onClick={() => setLegal('terms')}>Terms of Service</button>, acknowledge the <button type="button" className="text-button" onClick={() => setLegal('privacy')}>Privacy Notice</button>, and consent to the described collection and use of my data.</span><FieldError message={fieldError('termsAccepted')} /></label></>}
    {error && <p id="auth-error" className="form-error" role="alert">{error}</p>}
    <button className="primary-button full" disabled={loading}>{loading ? 'Just a moment…' : mode === 'login' ? 'Sign in' : 'Create account'}</button>
  </form><p className="switch-copy">{mode === 'login' ? 'New to Tempo?' : 'Already have an account?'} <button type="button" className="text-button" onClick={switchMode}>{mode === 'login' ? 'Create an account' : 'Sign in'}</button></p></div>{legal && <div className="modal-backdrop"><section className="modal legal-modal" role="dialog" aria-modal="true" aria-label={legalTitle}><div className="section-heading"><div><p className="eyebrow">Tempo · Version {PRIVACY_NOTICE_VERSION}</p><h2>{legalTitle}</h2></div><button className="icon-button" type="button" onClick={() => setLegal(null)} aria-label="Close">×</button></div>{legalContent.map(([heading, copy]) => <section key={heading} className="legal-section"><h3>{heading}</h3><p>{copy}</p></section>)}<button className="primary-button" type="button" onClick={() => setLegal(null)}>I understand</button></section></div>}</section></main>;
}

function Heatmap({ entries }: { entries: Dashboard['heatmap'] }) {
  const lookup = new Map(entries.map(item => [item.date, item.count]));
  const dates = Array.from({ length: 35 }, (_, i) => { const date = new Date(); date.setDate(date.getDate() - 34 + i); return date.toISOString().slice(0, 10); });
  const max = Math.max(1, ...entries.map(item => item.count));
  return <div className="heatmap" aria-label="Completions over the last five weeks">{dates.map(date => { const count = lookup.get(date) ?? 0; return <span key={date} title={`${date}: ${count} completion${count === 1 ? '' : 's'}`} className={`heat-cell level-${count === 0 ? 0 : Math.ceil((count / max) * 4)}`} />; })}</div>;
}

function HabitCard({ habit, onComplete, completed, busy }: { habit: HabitWithStreak; onComplete: () => void; completed: boolean; busy: boolean }) {
  return <article className="habit-card"><div className="habit-heading"><div><span className="frequency-label">{habit.frequency === 'weekly' ? `${habit.targetCount}× weekly` : 'Daily'}</span><h3>{habit.name}</h3><p>{habit.description}</p></div><div className="streak"><strong>{habit.streak.currentStreak}</strong><span>day streak</span></div></div><button className={completed ? 'complete-button done' : 'complete-button'} onClick={onComplete} disabled={busy || completed} aria-label={`Mark ${habit.name} complete`}>{busy ? 'Saving…' : completed ? 'Completed today' : 'Mark complete'}</button></article>;
}

function DashboardView({ token, refreshTick }: { token: string; refreshTick: number }) {
  const [dashboard, setDashboard] = useState<Dashboard | null>(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(true); const [completed, setCompleted] = useState<Set<string>>(new Set()); const [busyId, setBusyId] = useState(''); const [notice, setNotice] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const data = await api.dashboard(token); const streaks = await Promise.all(data.habits.map(habit => api.streak(token, habit.id))); setDashboard({ ...data, habits: data.habits.map((habit, index) => ({ ...habit, streak: streaks[index] })) }); } catch (caught) { setError(errorMessage(caught)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [token, refreshTick]);
  const complete = async (habit: HabitWithStreak) => { setBusyId(habit.id); setNotice(''); try { await api.complete(token, habit.id); setCompleted(old => new Set(old).add(habit.id)); setNotice(`${habit.name} is on the board for today.`); } catch (caught) { const apiError = caught as ApiError; if (apiError.code === 'DUPLICATE' || /already exists/i.test(apiError.message)) { setCompleted(old => new Set(old).add(habit.id)); setNotice('Already complete today — nicely done.'); } else setNotice(errorMessage(caught)); } finally { setBusyId(''); } };
  if (loading) return <Loading label="Gathering your progress…" />;
  if (error) return <ErrorState message={error} onRetry={() => void load()} />;
  if (!dashboard) return null;
  const statCards = [{ label: 'Active habits', value: dashboard.statistics.totalHabits }, { label: 'Current streaks', value: dashboard.statistics.activeStreaks }, { label: 'Completion rate', value: `${dashboard.statistics.averageCompletionRate}%` }];
  return <><header className="view-header"><div><p className="eyebrow">Today · {new Intl.DateTimeFormat(undefined, { weekday: 'long', month: 'long', day: 'numeric' }).format(new Date())}</p><h1>Keep the rhythm.</h1></div><button className="icon-button" onClick={() => void load()} aria-label="Refresh dashboard">↻</button></header>{notice && <p className="notice" role="status">{notice}</p>}<section className="stats-grid">{statCards.map(stat => <article className="stat-card" key={stat.label}><span>{stat.label}</span><strong>{stat.value}</strong></article>)}</section><section className="dashboard-grid"><article className="surface heatmap-card"><div className="section-heading"><div><p className="eyebrow">Last five weeks</p><h2>Every mark matters.</h2></div><span className="quiet-dot">{todayKey()}</span></div><Heatmap entries={dashboard.heatmap} /><div className="heatmap-key"><span>Less</span><i className="level-0" /><i className="level-2" /><i className="level-4" /><span>More</span></div></article><aside className="surface reflection"><span className="reflection-mark">“</span><p>Consistency is not intensity. It’s returning, again and again.</p><span>— a note for today</span></aside></section><section className="list-section"><div className="section-heading"><div><p className="eyebrow">Your habits</p><h2>Today’s gentle focus</h2></div><span className="muted">{dashboard.habits.length} total</span></div>{dashboard.habits.length === 0 ? <EmptyState title="Your space is ready." description="Add your first habit, then come back tomorrow." /> : <div className="habit-grid">{dashboard.habits.map(habit => <HabitCard key={habit.id} habit={habit} completed={completed.has(habit.id)} busy={busyId === habit.id} onComplete={() => void complete(habit)} />)}</div>}</section></>;
}

const blankHabit = { name: '', description: '', frequency: 'daily' as Frequency, targetCount: 1 };
function HabitForm({ initial, onSubmit, onCancel, saving }: { initial?: Habit; onSubmit: (payload: HabitPayload) => void; onCancel: () => void; saving: boolean }) {
  const [form, setForm] = useState(initial ? { name: initial.name, description: initial.description, frequency: initial.frequency, targetCount: initial.targetCount ?? 1 } : blankHabit);
  const submit = (event: FormEvent) => { event.preventDefault(); onSubmit({ name: form.name.trim(), description: form.description.trim(), frequency: form.frequency, ...(form.frequency === 'weekly' ? { targetCount: Number(form.targetCount) } : {}) }); };
  return <form className="habit-form" onSubmit={submit}><label>Name<input required maxLength={80} value={form.name} onChange={e => setForm({ ...form, name: e.target.value })} placeholder="Read before bed" autoFocus /></label><label>Why it matters<input required maxLength={180} value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} placeholder="Ten quiet minutes with a book" /></label><fieldset><legend>Rhythm</legend><div className="segmented">{(['daily', 'weekly'] as Frequency[]).map(option => <button key={option} type="button" className={form.frequency === option ? 'active' : ''} onClick={() => setForm({ ...form, frequency: option })}>{option}</button>)}</div></fieldset>{form.frequency === 'weekly' && <label>Times each week<input required type="number" min="1" max="7" value={form.targetCount} onChange={e => setForm({ ...form, targetCount: Number(e.target.value) })} /></label>}<div className="form-actions"><button type="button" className="secondary-button" onClick={onCancel}>Cancel</button><button className="primary-button" disabled={saving}>{saving ? 'Saving…' : initial ? 'Save changes' : 'Add habit'}</button></div></form>;
}

function HabitsView({ token, onChanged }: { token: string; onChanged: () => void }) {
  const [habits, setHabits] = useState<HabitWithStreak[]>([]); const [loading, setLoading] = useState(true); const [error, setError] = useState(''); const [editor, setEditor] = useState<Habit | 'new' | null>(null); const [saving, setSaving] = useState(false); const [removing, setRemoving] = useState('');
  const load = async () => { setLoading(true); setError(''); try { const data = await api.habits(token); const streaks = await Promise.all(data.map(habit => api.streak(token, habit.id))); setHabits(data.map((habit, index) => ({ ...habit, streak: streaks[index] }))); } catch (caught) { setError(errorMessage(caught)); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [token]);
  const save = async (payload: HabitPayload) => { setSaving(true); try { if (editor === 'new') await api.createHabit(token, payload); else if (editor) await api.updateHabit(token, editor.id, payload); setEditor(null); await load(); onChanged(); } catch (caught) { setError(errorMessage(caught)); } finally { setSaving(false); } };
  const remove = async (habit: Habit) => { if (!window.confirm(`Remove “${habit.name}”? This cannot be undone.`)) return; setRemoving(habit.id); try { await api.deleteHabit(token, habit.id); await load(); onChanged(); } catch (caught) { setError(errorMessage(caught)); } finally { setRemoving(''); } };
  if (loading) return <Loading label="Loading your habits…" />;
  return <><header className="view-header"><div><p className="eyebrow">Your practice</p><h1>Habits, at a glance.</h1></div><button className="primary-button" onClick={() => setEditor('new')}>+ Add habit</button></header>{error && <p className="form-error" role="alert">{error}</p>}{editor && <div className="modal-backdrop" role="presentation"><section className="modal" role="dialog" aria-modal="true" aria-label={editor === 'new' ? 'Add a habit' : 'Edit habit'}><div className="section-heading"><div><p className="eyebrow">{editor === 'new' ? 'New intention' : 'Refine habit'}</p><h2>{editor === 'new' ? 'Make it easy to start.' : 'Adjust the rhythm.'}</h2></div><button className="icon-button" onClick={() => setEditor(null)} aria-label="Close">×</button></div><HabitForm initial={editor === 'new' ? undefined : editor} onSubmit={payload => void save(payload)} onCancel={() => setEditor(null)} saving={saving} /></section></div>}<section className="list-section habits-list">{habits.length === 0 ? <EmptyState title="Start with one thing." description="A tiny, repeatable action is more than enough." action="Add a habit" onAction={() => setEditor('new')} /> : habits.map(habit => <article className="habit-row" key={habit.id}><div className="row-mark">{habit.frequency === 'daily' ? '◌' : '◍'}</div><div className="row-content"><h2>{habit.name}</h2><p>{habit.description}</p><span>{habit.frequency === 'daily' ? 'Daily' : `${habit.targetCount} times weekly`} · {habit.streak.currentStreak} day streak</span></div><div className="row-actions"><button className="secondary-button" onClick={() => setEditor(habit)}>Edit</button><button className="delete-button" disabled={removing === habit.id} onClick={() => void remove(habit)}>{removing === habit.id ? 'Removing…' : 'Delete'}</button></div></article>)}</section></>;
}

function ProfileView({ session, onLogout }: { session: Session; onLogout: () => void }) { return <><header className="view-header"><div><p className="eyebrow">Your account</p><h1>Keep it simple.</h1></div></header><section className="profile-card surface"><div className="avatar">{initials(session.user.email)}</div><div><h2>{session.user.email}</h2><p className="muted">Your private space for everyday practice.</p></div><span className="status-pill">Active session</span></section><section className="settings-section"><p className="eyebrow">Settings</p><div className="setting-row"><div><h2>Sign out</h2><p>End this session on this device.</p></div><button className="secondary-button" onClick={onLogout}>Sign out</button></div></section></> }
function Loading({ label }: { label: string }) { return <div className="state-box"><span className="spinner" /><p>{label}</p></div>; }
function ErrorState({ message, onRetry }: { message: string; onRetry: () => void }) { return <div className="state-box"><h2>We hit a pause.</h2><p>{message}</p><button className="secondary-button" onClick={onRetry}>Try again</button></div>; }
function EmptyState({ title, description, action, onAction }: { title: string; description: string; action?: string; onAction?: () => void }) { return <div className="empty-state"><div className="empty-symbol">✦</div><h3>{title}</h3><p>{description}</p>{action && <button className="primary-button" onClick={onAction}>{action}</button>}</div>; }

function AppShell({ session, onLogout }: { session: Session; onLogout: () => void }) {
  const [view, setView] = useState<View>('dashboard'); const [refreshTick, setRefreshTick] = useState(0); const content = useMemo(() => view === 'dashboard' ? <DashboardView token={session.token} refreshTick={refreshTick} /> : view === 'habits' ? <HabitsView token={session.token} onChanged={() => setRefreshTick(value => value + 1)} /> : <ProfileView session={session} onLogout={onLogout} />, [view, session, refreshTick]);
  return <div className="app-shell"><aside className="sidebar"><div className="brand">tempo<span>•</span></div><nav aria-label="Main navigation">{([['dashboard', 'Overview', '◫'], ['habits', 'Habits', '◎'], ['profile', 'Profile', '◌']] as const).map(([id, label, icon]) => <button key={id} className={view === id ? 'nav-item active' : 'nav-item'} onClick={() => setView(id)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-user"><span className="avatar small">{initials(session.user.email)}</span><span>{session.user.email}</span></div></aside><main className="content">{content}</main><nav className="mobile-nav" aria-label="Main navigation">{([['dashboard', 'Overview', '◫'], ['habits', 'Habits', '◎'], ['profile', 'Profile', '◌']] as const).map(([id, label, icon]) => <button key={id} className={view === id ? 'active' : ''} onClick={() => setView(id)}><span>{icon}</span>{label}</button>)}</nav></div>;
}

export default function App() { const [session, setSession] = useState<Session | null>(() => loadSession()); const authenticate = (next: Session) => { saveSession(next); setSession(next); }; const logout = async () => { if (session) { try { await api.logout(session.token); } catch { /* The local session must still end if the API is unavailable. */ } } clearSession(); setSession(null); }; return session ? <AppShell session={session} onLogout={() => void logout()} /> : <AuthScreen onAuthenticated={authenticate} />; }
